### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: Requested setting EMOJI_IMG_TAG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

### ISSUE THREAD

**Issue by jekeam** [carpedm20/emoji#220]
```
import emoji
print(emoji('Python is :thumbs_up:'))
```

Traceback (most recent call last):
  File "E:\YandexDisk\github\change_site_notify_bot\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-0e68c25c8259>", line 1, in <cell line: 1>
    import emoji
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\YandexDisk\github\change_site_notify_bot\venv\lib\site-packages\emoji\__init__.py", line 1, in <module>
    from .models import Emoji as emoji_class
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\YandexDisk\github\change_site_notify_bot\venv\lib\site-packages\emoji\models.py", line 14, in <module>
    from . import settings
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\YandexDisk\github\change_site_notify_bot\venv\lib\site-packages\emoji\settings.py", line 5, in <module>
    EMOJI_IMG_TAG = getattr(settings, 'EMOJI_IMG_TAG', (
  File "E:\YandexDisk\github\change_site_notify_bot\venv\lib\site-packages\django\conf\__init__.py", line 87, in __getattr__
    self._setup(name)
  File "E:\YandexDisk\github\change_site_notify_bot\venv\lib\site-packages\django\conf\__init__.py", line 67, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting EMOJI_IMG_TAG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by cvzi** [comment]
Can you explain in more detail when this happens and which version of python and of the module you are using?

**Comment by jekeam** [comment]
My mistake: I installed "emoji-django"
